sudo: required
services:
  - docker

before_install:
  - docker build -t hellobeastie/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hellobeastie/react-test npm run test

after_success:
  - docker build -t hellobeastie/multi-client ./client
  - docker build -t hellobeastie/multi-nginx ./nginx
  - docker build -t hellobeastie/multi-server ./server
  - docker build -t hellobeastie/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push hellobeastie/multi-client
  - docker push hellobeastie/multi-nginx
  - docker push hellobeastie/multi-server
  - docker push hellobeastie/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-2-317327324010
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY